name: Go

on:
  push:
    branches:
      - master
      - 'feature/**'
    tags:
      - *

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build_amd64

      - name: Upload markdown2confluence for docker build
        uses: actions/upload-artifact@v1
        with:
          name: docker-binary
          path: markdown2confluence

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build multiarch
        run: make -j4 release

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Darwin 386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./markdown2confluence-darwin-386
          asset_name: markdown2confluence-darwin-386
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Linux 386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./markdown2confluence-linux-386
          asset_name: markdown2confluence-linux-386
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Linux amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./markdown2confluence-linux-amd64
          asset_name: markdown2confluence-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Linux arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./markdown2confluence-linux-arm64
          asset_name: markdown2confluence-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Linux arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./markdown2confluence-linux-arm
          asset_name: markdown2confluence-linux-arm
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Windows amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./markdown2confluence-windows-amd64
          asset_name: markdown2confluence-windows-amd64
          asset_content_type: application/octet-stream

      - name: Save output URL
        shell: bash
        run: echo -n "${{ steps.create_release.outputs.upload_url }}" > output-url.txt

      - name: Upload output URL
        uses: actions/upload-artifact@v1
        with:
          name: output-url
          path: output-url.txt

  publish-docker:
    name: Publish Docker
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Download markdown2confluence amd64
        uses: actions/download-artifact@v1
        with:
          name: docker-binary

      - name: Move binary
        run: |
          mv docker-binary/markdown2confluence markdown2confluence
          chmod 755 markdown2confluence

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :latest
        run: |
          docker build -t terrycain/markdown2confluence:latest .
          docker tag terrycain/markdown2confluence:latest terrycain/markdown2confluence:${{ steps.get_version.outputs.version }}

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push terrycain/markdown2confluence:latest

      - name: Push to docker hub :${{ steps.get_version.outputs.version }}
        uses: actions-hub/docker@master
        with:
          args: push terrycain/markdown2confluence:${{ steps.get_version.outputs.version }}
